---
label: Metadata
hide_body: false
fields:
- type: text
  name: title
  label: Title
  description: Titre du site
  config:
    required: true
- name: caption
  type: text
  config:
    required: false
  label: Caption
  description: LÃ©gende du logo
- name: opening
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Opening
  description: Les horaires d'ouverture
